project:
  title: "PKTu"
  type: website
  output-dir: ../docs

website:
  back-to-top-navigation: true
  sidebar:
    style: "floating"
    search: true
    border: true
    contents:
      - text: Home
        href: index.qmd
      - text: Quality control
        href: qc.qmd
      - text: Differential Expression
        href: de.qmd
      - text: GSEA
        href: gsea.qmd
      - text: GSEA (DAR-corrected)
        href: gsea_dar.qmd
      - text: DAR
        href: dar.qmd
    tools:
      - icon: github
        href: https://github.com/baerlachlan
  search:
    location: sidebar
    type: overlay

format:
  html:
    theme:
      light: flatly
      dark: darkly
    # css: custom.css
    toc: true