set-threads:
  ## refs
  genome_get: 1
  genome_index: 1
  annotation_get: 1
  star_index: 8
  ## fastqc
  fastqc_raw: 1
  fastqc_trim: 1
  fastqc_align: 1
  ## trim
  trim_se: 4
  trim_pe: 4
  trim_md5: 1
  ## merge
  merge: 1
  merge_md5: 1
  ## align
  align: 16
  align_md5: 1
  ## count
  count: 8

set-resources:
  ## refs
  genome_index:
    runtime: 10
    mem_mb: 1024
  star_index:
    runtime: 30
    mem_mb: 32768
  ## fastqc
  fastqc_raw:
    runtime: 30
    mem_mb: 2048
  fastqc_trim:
    runtime: 30
    mem_mb: 2048
  fastqc_align:
    runtime: 30
    mem_mb: 2048
  ## trim
  trim_se:
    runtime: 30
    mem_mb: 4096
  trim_pe:
    runtime: 30
    mem_mb: 4096
  trim_md5:
    runtime: 60
    mem_mb: 1024
  ## merge
  merge:
    runtime: 30
    mem_mb: 4096
  merge_md5:
    runtime: 60
    mem_mb: 1024
  ## align
  align:
    runtime: 60
    mem_mb: 32768
    slurm_extra: "'--gres=tmpfs:100G'"  # Needs to be about 5x total input fastq size
  align_md5:
    runtime: 120
    mem_mb: 1024
  ## count
  count:
    runtime: 60
    mem_mb: 4096
